import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// layout.js は各フォルダ階層で必須ではない
// 配置することで、そのフォルダ階層以下の全てのページの外側に被さるコンポーネントを定義することができる
// app/layout.js に定義したコンポーネントは、全てのパスの外側に被せられることになる
// Webページにおいて、ルートパス（ / ）以下の全ての階層において、必ず表示されていてほしい、最も外側のコンポーネントといえば、そう、<html> や <body> ですね
// App Routerでは、<html> や <body> を定義するための特別なコンポーネントを用意するのではなく、任意の階層の外側に被せるための layout.js という仕組みを使って、HTMLとしての外側を定義している
export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  );
}
